"""Generate packaging app icons from the KoeKichi mascot artwork (SPEC §18.2).

This is a one-off developer utility, not run on every build. It writes:

- packaging/icon.png   (from app_icon_source.png, upscaled if needed)
- packaging/icon.icns  (macOS only, multi-resolution, built with `iconutil`)
- packaging/icon.ico   (Windows only, via Qt's built-in ICO writer)

Source artwork: packaging/app_icon_source.png (1024x1024, the KoeKichi
raccoon-with-leaf mascot design master). packaging/icon.icns and
icon.ico in this repo were copied directly from the pre-built
KoeKichi.iconset / koe-kichi.icns / koe-kichi.ico assets (same source
design) rather than regenerated by this script, to avoid any quality
loss from re-encoding. Re-run this script only if app_icon_source.png
is replaced with a new master image.

Note: this app icon is intentionally different from the tray/menu-bar
icon, which is a separately hand-drawn monochrome leaf glyph (see
koekichi/ui/tray.py) chosen to avoid visual confusion with the OS's own
menu-bar audio icons.

Usage:
    QT_QPA_PLATFORM=offscreen uv run python packaging/make_icons.py
"""

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import QApplication

OUT_DIR = Path(__file__).resolve().parent
SOURCE_PNG = OUT_DIR / "app_icon_source.png"

# macOS iconset requires exactly these base sizes, each with a @2x variant
# (iconutil derives 16/32/64/128/256/512/1024 coverage from this set).
_ICNS_BASE_SIZES = (16, 32, 128, 256, 512)


def load_source() -> QPixmap:
    pixmap = QPixmap(str(SOURCE_PNG))
    if pixmap.isNull():
        raise RuntimeError(f"Failed to load source artwork: {SOURCE_PNG}")
    return pixmap


def scaled_icon(source: QPixmap, size: int) -> QPixmap:
    """Smoothly scale the source mascot artwork to `size`x`size`."""
    return source.scaled(
        size, size, Qt.KeepAspectRatio, Qt.SmoothTransformation
    )


def make_icns(source: QPixmap, out_path: Path) -> None:
    """Build a multi-resolution .icns via the macOS `iconutil` CLI."""
    if not shutil.which("iconutil"):
        raise RuntimeError("iconutil not found; this step requires macOS.")

    with tempfile.TemporaryDirectory() as tmp:
        iconset = Path(tmp) / "icon.iconset"
        iconset.mkdir()
        for base in _ICNS_BASE_SIZES:
            scaled_icon(source, base).save(
                str(iconset / f"icon_{base}x{base}.png"), "PNG"
            )
            scaled_icon(source, base * 2).save(
                str(iconset / f"icon_{base}x{base}@2x.png"), "PNG"
            )
        subprocess.run(
            ["iconutil", "-c", "icns", str(iconset), "-o", str(out_path)],
            check=True,
        )


def make_ico(source: QPixmap, out_path: Path) -> None:
    """Build a .ico via Qt's built-in ICO image writer (no Pillow needed)."""
    if not scaled_icon(source, 256).save(str(out_path), "ICO"):
        raise RuntimeError(f"Qt failed to write {out_path}")


def main() -> None:
    app = QApplication.instance() or QApplication(sys.argv)

    source = load_source()

    png_path = OUT_DIR / "icon.png"
    if not scaled_icon(source, 1024).save(str(png_path), "PNG"):
        raise RuntimeError(f"Failed to write {png_path}")
    print(f"Wrote {png_path}")

    if sys.platform == "darwin":
        icns_path = OUT_DIR / "icon.icns"
        make_icns(source, icns_path)
        print(f"Wrote {icns_path}")
    elif sys.platform == "win32":
        ico_path = OUT_DIR / "icon.ico"
        make_ico(source, ico_path)
        print(f"Wrote {ico_path}")
    else:
        print("Not macOS/Windows: only icon.png was generated.")

    _ = app  # keep the QApplication alive until pixmap.save() calls finish


if __name__ == "__main__":
    main()
